[versions]

agp = "8.1.0"

# Kotlin
kotlin = "1.8.10"
kotlinCoroutines = "1.6.4"
kotlinxSerialization = "1.5.0"

# Core
commonsImaging = "1.0-alpha2"
appcompat = "1.4.1"
camerax = "1.4.0"

# NFC
jmrtd = "0.7.42"
scubaSmartCard = "0.0.23"

# IAD
protobufLite = "3.25.5"

# MLKit
mlKitFace = "16.1.7"
mlKitText = "16.0.1"

# UI/UX
materialDesign = "1.5.0"
viewbinding = "8.1.0"
nav = "2.5.3"
constraintLayout = "2.1.3"
fragment = "1.4.0"
lifecycle = "2.4.1"

# Tools
apiValidator = "0.13.0"
detekt = "1.18.1"
dokka = "1.8.10"
leakcanary = "2.9.1"
jacoco = "0.8.12"

# Test
junit = "4.13.2"
mockito = "3.12.4"
mockk = "1.12.4"
espresso = "3.4.0"
okhttp = "4.10.0"
robolectric = "4.11.1"
uiautomator = "2.2.0"
androidxTestExtJunit = "1.1.3"
androidxTest = "1.4.0"

[libraries]
# Kotlin
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

# Core
commons-imaging = { module = "org.apache.commons:commons-imaging", version.ref = "commonsImaging" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# CameraX
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "camerax" }

# NFC
jmrtd = { module = "org.jmrtd:jmrtd", version.ref = "jmrtd" }
scuba-sc-android = { module = "net.sf.scuba:scuba-sc-android", version.ref = "scubaSmartCard" }

# IAD
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufLite" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufLite" }

# MLKit
mlkit-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlKitText" }
mlkit-face-detection = { module = "com.google.mlkit:face-detection", version.ref = "mlKitFace" }

# UI/UX
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "nav" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "viewbinding" }
material = { module = "com.google.android.material:material", version.ref = "materialDesign" }

# Test
androidx-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "nav" }
androidx-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
junit = { module = "junit:junit", version.ref = "junit" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
apiValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "apiValidator" }
